name: MyGithubActions-Basics

on:
  push:
    branches:
      - master 
  
jobs:
  mytesting:
    runs-on: ubuntu-latest

    steps:
     - name: Privet Hello Message
       run : echo "Hello world! from GitAction Testing!"
    
  mydeploy:
    runs-on: ubuntu-latest
    needs: [ mytesting ]
    
    steps:
     - name: Privet Hello Message
       run : echo "Hello world! from GitAction Dep!"
