name: MyGithubActions-Basics
env:
  APPLICATION_NAME    : "MyProgram"
  DEPLOY_PACKAGE_NAME : "deploy-ver-${{ github.sha }}"

on:
  push:
    branches:
      - master 
  
jobs:
  mytesting:
    runs-on: ubuntu-latest

    steps:
     - name: Git clone Actions
       uses: actions/checkout@v1
       
     - name: List folder
       run : ls -la 
       
     - name: Execute commands
       run : |
        touch  ${{ env.APPLICATION_NAME }}.tx
        
      
  mydeploy:
    runs-on: ubuntu-latest
    needs: [ mytesting ]
    
    steps:
     - name: Privet Hello Message
       run : echo "Hello world! from GitAction Dep!"
     - name: Execute commands
       run: |
        pwd > 123.tx
        cat 123.tx
        echo "Deploy name: ${{ env.DEPLOY_PACKAGE_NAME }}"
