name: MyGithubActions-Basics
env:
  APPLICATION_NAME    : "MyProgram"
  DEPLOY_PACKAGE_NAME : "deploy-ver-${{ github.sha }}"

on:
  push:
    branches:
      - master 
  
jobs:
  mytesting:
    runs-on: ubuntu-latest

    steps:
     - name: Git clone Actions
       uses: actions/checkout@v1
       
     - name: List folder
       run : ls -la 
       
     - name: Execute commands
       run : |
        touch  ${{ env.APPLICATION_NAME }}.tx
        
      
  mydeploy:
    runs-on: ubuntu-latest
    needs: [ mytesting ]
    env: 
      VAR1 : "This is Variable 1"
      VAR2 : "This is Variable 2"
    
    steps:
     - name: Print env variables
       run : |
        "Var1 = ${{ env.VAR1 }}"
        "Var2 = ${{ env.VAR2 }}"
        "Var3 = $LOCAL_VAR
       env:
        LOCAL_VAR : "This is local variable"
     - name: Privet Hello Message
       run : echo "Hello world! from GitAction Dep!"
     - name: Execute commands
       run: |
        pwd > 123.tx
        cat 123.tx
        echo "Deploy name: ${{ env.DEPLOY_PACKAGE_NAME }}"
